# Project information
site_name: 'Tabix'
site_description: 'Tabix DB Gui'
site_author: 'Igor Strykhar'
site_url: 'https://tabix.io/doc'

# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/smi2/tabix.ui'
edit_uri: 'edit/master/manual/docs/'
# Copyright
copyright: 'Copyright &copy; 2017 Igor Strykhar '

# Documentation and theme
theme: 'material'

# Options
extra:
  logo: 'img/logo.png'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Menlo'
    code: 'Roboto Mono'
  social:
    - type: 'github'
      link: 'https://github.com/smi2/tabix.ui'
    - type: 'twitter'
      link: 'https://twitter.com/tabix_io'

# Google Analytics
#google_analytics:
#  - 'UA-XXXXXXXX-X'
#  - 'auto'
site_favicon: 'favicon.ico'
extra_css:
  - 'stylesheets/extra.css'
# Extensions
markdown_extensions:
  - admonition
  - codehilite(guess_lang=false)
  - footnotes
  - meta
  - toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
copyright: Copyright 2017 Igor Strykhar,Ivan Kudinov,SMI2 LLC and other contributors<script type="text/javascript">
                  (function (d, w, c) {
                      (w[c] = w[c] || []).push(function() {
                          try {
                              w.yaCounter43559384 = new Ya.Metrika({
                                  id:43559384,
                                  clickmap:true,
                                  trackLinks:true,
                                  accurateTrackBounce:true,
                                  webvisor:true,
                                  trackHash:true
                              });
                          } catch(e) { }
                      });
                      var n = d.getElementsByTagName("script")[0],
                          s = d.createElement("script"),
                          f = function () { n.parentNode.insertBefore(s, n); };
                      s.type = "text/javascript";
                      s.async = true;
                      s.src = "https://mc.yandex.ru/metrika/watch.js";
                      if (w.opera == "[object Opera]") {
                          d.addEventListener("DOMContentLoaded", f, false);
                      } else { f(); }
                  })(document, window, "yandex_metrika_callbacks");
              </script>
              <noscript><div><img src="https://mc.yandex.ru/watch/43559384" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
